interfaces/remoteOperatorUI/VideoFileManager.js, interfaces/remoteOperatorUI/VideoProcessManager.js, interfaces/remoteOperatorUI/VideoServer.js, interfaces/remoteOperatorUI/ffmpegInterface.js, interfaces/remoteOperatorUI/index.js, interfaces/remoteOperatorUI/makeStreamRouter.js, interfaces/remoteOperatorUI/server.js, interfaces/remoteOperatorUI/utilities.js, interfaces/remoteOperatorUI/videoConstants.js, package-lock.json, package.json
Updates the remoteOperatorUI interface so that the streamRouter additionally sends rgb+depth+pose data to a VideoServer class, which is composed of a few different modules that process the data using ffmpeg and write it to the filesystem. (See the server.js file for where the integration happens)
A video will only be recorded if the app sends a startRecording message over the web socket. This is only the backend, I'll make additional PRs for the app and to add the timeline playback UI to the frontend.
Videos are saved in spatialToolbox/.identity/virtualizer_recordings. The recorded videos can be accessed through the REST interface at localhost:8081/virtualizer_recordings
=> 3d video recording backend

interfaces/remoteOperatorUI/VideoFileManager.js, interfaces/remoteOperatorUI/VideoProcessManager.js, interfaces/remoteOperatorUI/VideoServer.js
accidentally pushed a bug in my last PR, server would crash from non-recursive mkdir if device disconnects without having ever recorded in the past to set up the dirs
=> fixes bug when new devices disconnect without starting any recordings

content_scripts/VirtualCamera.js, content_scripts/desktopCamera.js
effectively moves the camera back a little bit to improve the alignment of the FoVs
side note: currently the aspect ratio of the remote operator window should be roughly the same as the rgb image (I believe a 4x3 ratio (1080x720)), otherwise the canvas is stretched
=> adjust point where 2d video canvas appears

content_scripts/CameraVis.js
Uses the point cloud mesh to improve the adaptability of the first person view, switching to a first person mode shader which disables opacity and depth occlusion to be essentially a 2d canvas. Using this approach allows the visualization to adapt to any aspect ratio or rotation.
=> Use virtualizer mesh in first person view; Allow switching camera shader mode

content_scripts/VirtualCamera.js, content_scripts/desktopAdapter.js, content_scripts/desktopCamera.js, content_scripts/desktopRenderer.js, content_scripts/desktopStats.js, content_scripts/multiclientUI.js, content_scripts/setupMenuBar.js
- Optimizes camera to work with an avatar object
- Adds SHIFT keyboard shortcut to trigger laser beam while held down
- simplifies multiclientUI icosahedron into a smaller cube (for now – still could use improvement but looking for something more subtle) 
Requires https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/243
=> Support for avatar objects + laser beams

content_scripts/VirtualCamera.js, content_scripts/desktopAdapter.js, content_scripts/desktopCamera.js
The curve that the VirtualCamera follows (behind the virtualizer) when you zoom in and out now ignores the "steering wheel" roll of the phone, so that it works just as well in portrait or landscape. Previously in portrait, the curve would sweep out to the side instead of vertically.
Additionally, the further you zoom out, the less the up-down tilt of the virtualizer affects your perspective. This results in very smooth birds-eye following experiences. But as you zoom in, the weight of the virtualizer's up-down pitch scales from 0 to 1, such that as you approach the first-person perspective you are fully matching the virtualizer (yaw and pitch) perspective (still ignoring roll) – centering the "2D" video on the screen when it appears.
I also cleaned up and reorganized VirtualCamera.js and …
=> Stabilize the camera following curve (regardless of portrait or landscape)

content_scripts/VirtualCamera.js
Pretty happy with this update! There was a problem when you rotated the camera when following, because the camera focus target is far away from the virtualizer. Snaps the camera focus to 1 meter in front of the virtualizer when you rotate/pan away. Slightly complicated code to get around various edge cases.
New behavior:
Old behavior:
=> Improved camera follow "breakaway" behavior

content_scripts/VirtualCamera.js
Has an issue where right-click rotating out of first person mode drops the camera at a bad location
=> Exit first person camera on mouse input

content_scripts/desktopCamera.js
Remains a constant max size (see screenshot) rather than filling up too much of the viewport
=> scale down the blue icon in the center of the screen if you get too close

content_scripts/CameraVis.js, content_scripts/desktopCamera.js, content_scripts/desktopRenderer.js
Goes with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/319
Updates the ViewFrustums in the threejsInterface with the camera position and orientation of each virtualizer, and uploads the resulting geometry to the shader uniforms to discard points underneath the pointclouds.
I'm apparently tired and accidentally pushed my branch to main while rebasing, but this should also hopefully fix any weird state from that push. 💀
=> Utilize area target frustum culling shader

content_scripts/CameraVis.js, content_scripts/desktopRenderer.js
Can be used to shorten the culling frustum if you're looking at a wall/object that fills your screen.
=> CameraVis stores maxDepthMeters on each update

content_scripts/VirtualCamera.js
In combination with last week's userinterface PR, this will place tools at the camera focus point (the little blue dot that you orbit around) if it doesn't find a suitable projected location on the area target mesh. Old method was very haphazard and could place tools at an unpredictable distance from camera.
=> adjust the drop distance for new tools to always be placed at the camera focus point (if not anchored to mesh)

content_scripts/CameraVis.js, content_scripts/desktopAdapter.js, content_scripts/desktopRenderer.js
Feels a bit indirect to access the webRTCCoordinator this way, but this seems to work
=> mute/unmute implementation for remote operator by intercepting appFunctionCall for mute/unmute

content_scripts/desktopAdapter.js
Didn't realize this was only half-implemented and probably led to performance issues on remote operator, as many worlds would all load in even tho only the primary world's mesh would render.
=> Properly set primaryWorld based on ?world query item

content_scripts/CameraVis.js
On slow networks, the cameraVis cameras reset to origin and their pointclouds disappear if they didn't receive an update in the last 5 seconds. I'm sure there's a better solution overall to make the connection more reliable, but for now we could increase the timeout value if you want to minimize this.
=> adds a constant to set an increased connection timeout for the cameraVis

content_scripts/desktopAdapter.js
After so many years of procrastinating this feature, we can now resize the remote operator window without having to reload the page.
Requires: https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/388
=> recalculates projection matrix when onWindowResized is triggered

content_scripts/CameraVis.js, content_scripts/desktopRenderer.js, content_scripts/setupMenuBar.js
Couldn't bring myself to remove them entirely, but defaults the frustum cutouts to not be active, and adds a menu item to turn it on
Requires https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/418
=> default view frustum cutouts to disabled; toggle in View menu turns on frustum cutouts

content_scripts/VirtualCamera.js, content_scripts/desktopCamera.js, content_scripts/setupMenuBar.js, content_styles/remoteOperator.css
Proudly presenting the new remote operator off-center camera:
1. RMB on the AreaTarget adds a "focus point" green cube, and camera rotates around this off-center focus point
2. MMB pan function remains unchanged
3. Mouse wheel scroll zooms the camera towards the focus point
4. Press G to instantly zoom & focus on the focus point
=> Remote operator off-center camera

content_scripts/VirtualCamera.js, content_scripts/desktopCamera.js
Change cameraTargetElement to rotateCenterElement, to match the new off-center camera system. Have rotateCenterElement's matrix constantly updates to focusTargetCube position. Works in conjunction with the new userinterface spatialCursor addToolAtScreenCenter() update.
=> Steve rotate center element update

content_scripts/VirtualCamera.js
3 GUI imrpovements:
1. using ESC key is equivalent to F key when exiting fly mode
2. added "G -- focus" in the keyboard control prompt when switching modes
3. zooming out no longer rotates the camera, instead just zooms out in a straight line. I also made the zoom in/out to the focus point faster
=> Esc key, g focus, & zooming out fixes

content_scripts/VirtualCamera.js
Turns out that the new camera system uses the three js scene coords space. The camera following position and target should apply the inverse ground plane matrix to get back to the right spot. Thanks Ben for the inspo.
=> Fixed remote operator following camera position below bug

content_scripts/KeyboardListener.js, content_scripts/MenuBar.js, content_styles/remoteOperator.css
1) Keyboard shortcuts no longer trigger if extra modifiers are held (no more hiding model when opening a new tab)
2) Menu Bar Items now support modifiers if desired
=> Menu modifier shortcuts

content_scripts/VirtualCamera.js, content_scripts/desktopCamera.js
Uses ALT+[1-0] to save the current camera position into local storage.
Uses SHIFT+[1-0] to load the corresponding saved position from local storage.
Integrates with the camera movement and has the same smoothing applied.
Also adds a menu item for ALT+1 and SHIFT+1, the others aren't listed in order to avoid clutter.
=> Added ability to save and load camera positions

content_scripts/VirtualCamera.js
1. Fixed Virtual Camera zooming in bug (sometimes, camera position is closer to focus point than target position, causing it to never focus on focus point when zooming in).
2. Adjust focus() zoomFactor, to make focus() zoom in closer to the mesh
=> Fine tune Virtual Camera focus parameters

content_scripts/CameraVis.js
Fixed a bug - need to convert principal point from image Y-axis bottom-to-top in Vuforia to top-to-bottom in OpenGL.
Related to https://github.com/ptcrealitylab/vuforia-spatial-toolbox-ios-swift/pull/404
=> 3D video - principal point fix 

content_scripts/VirtualCamera.js, content_scripts/desktopAdapter.js, content_scripts/desktopCamera.js, content_scripts/desktopRenderer.js, content_scripts/desktopStats.js, content_scripts/multiclientUI.js, content_scripts/setupMenuBar.js, content_styles/remoteOperator.css
Adds tap, one-and-two finger drag, and pinch controls to navigate the camera in a mobile web browser. Tap without dragging to set the focus cube position. Drag with one finger to rotate. Two finger drag to pan, two finger pinch to zoom.
Adds a variety of countermeasures to try to prevent the native iOS gesture recognitions that swap tabs and pull-to-refresh and zoom out the page.
Also swaps the gltf to use the default material instead of the advanced animated/frustum-culled material on mobile browsers, to improve performance.
=> Mobile remote operator

content_scripts/VirtualCamera.js
Fix a bug where mouse wheel (not touchpad) scrolls so fast that camera cannot focus to the focus point, instead jumping back and forth around it
=> Mouse wheel zooming bug fix

content_scripts/VirtualCamera.js, content_scripts/setupMenuBar.js
Previously the F keyboard shortcut was handled separately from other keyboard shortcuts, and didn't appear in the menu bar. Now it shows in the menu to help remind the user of which key to press to activate it.
=> add fly mode keyboard shortcut to Camera menu

content_scripts/desktopAdapter.js
Works on 2D tools that don't set `spatialInterface.alwaysFaceCamera(true)` (all of them do, but here's a demo of how it looks if I turned off that setting on the video tool)
More importantly for our current demos, allows the remote operator to rotate the 3D onshape models by pressing the R key while dragging them:
Somewhat similar to how the remote operator can press the S key while dragging to scale tools. This could probably use a more thoughtful UI overhaul at some point – this is more of a shortcut I'm taking for now to add the functionality.
=> pressing R key while dragging a tool rotates the tool towards your camera view on remote operator

content_scripts/VirtualCamera.js, content_scripts/desktopRenderer.js
Swaps the area target mesh material to the simpler one on all devices, since we aren't currently using the frustum cutout shader. This improves performance. Also updates the sceneGraph more immediately after the camera updates.
=> small performance optimizations

content_scripts/VirtualCamera.js
Keeps rotateFactor in the rotation calculations to slow down rotations while looking down, but removes it from the panning calculations so that you can pan at full speed regardless of what angle you're viewing from. I don't think it's needed here, but let me know if you remember it being necessary.
Before:
After:
=> remove rotateFactor from strafe, so you can move at full speed while looking down

content_scripts/VirtualCamera.js
Other keyboard shortcuts have this guard, but the camera focus shortcut was missing it. (I noticed the issue when typing a G into the edit username textfield)
=> Ignore G key (camera focus shortcut) while tool or other input is capturing keyboard events

content_scripts/KeyboardListener.js
I was debugging why sometimes the keyboard shortcuts stop working. Looks like it was because if any of the modifier keys gets "stuck" down then the menu item key shortcuts don't match the KeyboardListener's state anymore so the callbacks don't trigger. Listening to blur events on the window seems to fix this in case a key was pressed down but the window lost focus before the key is released.
=> KeyboardListener.js listens for blur events to reset key states

content_scripts/CameraVis.js
simplify the render loop by eliminating the need for layers, rendering the whole scene at once instead of multiple times with different layers
depends on:
https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/640
=> single layer grid

content_scripts/VirtualCamera.js
Prevents camera control prompts from trying to show in the AR app when you transition to VR mode
=> Fix bug in the AR<>VR mode transition causing app to freeze

content_scripts/CameraVis.js
This speeds up cameravis rendering but is causing problems (frozen image and depth) for Safari.
=> Disable fast texture upload hack

content_scripts/setupMenuBar.js
Should make things easier when we need to download target data, etc, from a mobile-hosted or cloud-hosted world
=> adds Download World Object button to developer menu, for convenience

content_resources/memory-add.svg, content_scripts/CameraPositionMemoryBar.js, content_scripts/MenuBar.js, content_scripts/desktopCamera.js, content_scripts/setupMenuBar.js, content_styles/remoteOperator.css
Trying not to spend too much time for this as it's just a fun convenience feature, but I think I've covered the main functionality:
- Integrates with Dan's existing save/load camera perspectives
- Saves a thumbnail of the current splat canvas or threejs canvas in the selected slot
- Stores the perspectives per-world in localStorage, and loads them back when refreshed
- Includes some error handling to delete old thumbnails from local storage if you've exceeded a certain storage limit
- Can press the `.` key or use the menu bar item to toggle the UI
Requires: https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/745
=> Camera perspective memory bar – UI for saving/loading camera positions

content_scripts/setupMenuBar.js
The menu item gets added instead in the spatial-ai-addon `content_scripts/index.js:addMenuItemIfAvailable` only if it can successfully ping the language service https://github.com/ptcrealitylab/spatial-ai-addon/pull/2
=> remove AI Assist from MenuBar; add it in spatial-ai-addon if connection successful

content_scripts/VirtualCamera.js
Slight optimization while you're following another user, to only do some extra updates to the scene if the person you're following actually moved, instead of every frame.
Works best with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/770 and https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/1125
=> VirtualCamera only applies matrix from lockOnMode if it changes
