ptcrealitylab/vuforia-spatial-remote-operator-addon

- .gitignore
- content_scripts/KeyboardListener.js
- content_scripts/VirtualCamera.js
- content_scripts/desktopAdapter.js
- content_scripts/desktopCamera.js
- content_scripts/desktopRenderer.js
- content_scripts/desktopStats.js
- content_styles/remoteOperator.css
- package-lock.json
- package.json
If the area target has a target.glb file uploaded, renders that as a static model. Press T to toggle to volumetric realtime view. Refactors and simplifies desktopCamera.js by using new VirtualCamera.js and KeyboardListener.js classes. Fixes some other small bugs.
> Volumetric mode + static model mode

- content_scripts/desktopAdapter.js
- content_scripts/desktopRenderer.js
Requires https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/185
> binds keyboard P key to toggle positioning mode for surface anchors

- content_scripts/SocketDataSource.js
Adds try catch statement to prevent server to crash if message is not in json format
> Error handling in websocket message parsing

- interfaces/remoteOperatorUI/server.js
Prevent server from crashing if the message received in the webscoket is not in json format
> Error handling when receiving websocket message

- content_scripts/VirtualCamera.js
Rotating around the target point is accomplished by moving the camera orthogonally to the lookAt vector, which updates each frame to point towards the center point again. This doesn't guarantee that the distance between the camera and center point stays the same (moving faster = more drift).
I added a step to lock it back to the original zoom level when rotating, rather than doing anything too fancy with a spherical coordinate system.
> fix camera zoom level if it drifts too far away while you are rotating the camera

- interfaces/remoteOperatorUI/makeStreamRouter.js
- interfaces/remoteOperatorUI/server.js
update the socket listening for startRecording and stopRecording so that userinterface can directly send the message without going thru the swift code intermediary
> Simplify startRecording/stopRecording sockets

- content_scripts/CameraVis.js
- content_scripts/RealityZoneViewer.js
- content_scripts/desktopRenderer.js
Use the state of the Spaghetti Map, Point Clouds, and Toggle Paths buttons to set the state of their corresponding features
> fix toggle states for several menu buttons

- content_scripts/CameraVis.js
- content_scripts/VideoPlaybackCoordinator.js
- content_scripts/WebRTCCoordinator.js
- content_scripts/webrtc-adapter.js
- interfaces/remoteOperatorUI/makeStreamRouter.js
Not testable without changes to the ios app but this should coexist nicely with the existing approach
> Add support for color+depth over webrtc

- content_scripts/CameraVis.js
- content_scripts/WebRTCCoordinator.js
- content_scripts/desktopRenderer.js
- content_styles/remoteOperator.css
- Add holographic shader mode
- Send and receive audio over WebRTC
- Only grey out background on desktop
- Fix scrolling by hiding everything outside of viewport
> Various improvements

- content_scripts/TimelineView.js
- content_scripts/setupMenuBar.js
Requires https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/228
> when menubar is added, set screenTopOffset to its height

- content_scripts/VirtualCamera.js
- content_scripts/desktopAdapter.js
- content_scripts/desktopCamera.js
rolling back the intensity of the change I made, it tipped the balance a bit too far.
> adjust min_dist to be less bad for closeup objects

- content_scripts/VirtualCamera.js
- content_scripts/desktopCamera.js
- content_scripts/desktopRenderer.js
I figured out why it looks so much better on your local setup :D
> Pass floorOffset to desktopCamera

- content_scripts/VirtualCamera.js
- content_scripts/desktopAdapter.js
Updates remote-operator to work with new three.js camera system
Requires https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/235
> Three js camera paradigm

- content_scripts/desktopAdapter.js
one-line change for updated parameter
> updates SettingToggle to use new options

- content_scripts/VirtualCamera.js
- content_scripts/desktopCamera.js
- content_scripts/desktopRenderer.js
Preserves the distance to camera and first person vs third person rendering mode
> Left+Right arrow keys to switch following targets (if multiple virtualizers)

- content_scripts/desktopAdapter.js
- content_styles/remoteOperator.css
Corresponding update for https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/251
> make groundplane show in grey and on by default on remote operator

- content_scripts/desktopAdapter.js
- content_scripts/multiclientUI.js
- content_scripts/setupMenuBar.js
Required for compatibility with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/255
> update for new avatar namespace

- content_scripts/CameraVis.js
- content_scripts/RealityZoneVoxelizer.js
- content_scripts/desktopRenderer.js
- content_scripts/setupMenuBar.js
Updates the voxelizer to have a toggleable menu item and work with the new depth representation
> Support Voxelizer as optional service

- content_scripts/desktopRenderer.js
Requires https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/270
> Don't render tools until the world mesh finishes loading

- content_scripts/RealityZoneVoxelizer.js
(requesting review more as a heads-up that there are differences)
> Update for three 142 version of buffergeometryutils

- content_scripts/CameraVis.js
- content_scripts/WebRTCCoordinator.js
Lying to threejs for a 4% overall performance increase
> Minor depth shader improvements

- content_scripts/KeyboardListener.js
Goes with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/294 to fix keyboard shortcuts in browser
> removes event.preventDefault from KeyboardListener.js

- content_scripts/desktopAdapter.js
- content_scripts/desktopCamera.js
- content_scripts/desktopRenderer.js
- content_scripts/desktopStats.js
- content_scripts/multiclientUI.js
instead of a duplicate (outdated) remote operator function. better for iPad detection
> updates to use userinterface isDesktop function

- content_scripts/desktopAdapter.js
- content_scripts/setupMenuBar.js
- content_styles/remoteOperator.css
Light Mode has a light background, green header, and grey groundplane lines instead of yellow. Might look better for certain scans / use cases
> adds MenuBar item to toggle DarkMode on/off (defaults to dark mode)

- content_scripts/desktopRenderer.js
- content_scripts/setupMenuBar.js
Added toggle to display human poses. I found it useful when interested in 3D video streams only without any skeletons over them.
Swapped 'Point clouds' to '3D videos' in menu. I think it less misleading but general enough to cover different options how to visualise RGBD streams.
> Human tracking multiple cameras

- content_styles/remoteOperator.css
- small style change to allow tooltips to appear under transparent prompts cards
> added pointer-events: none to camera prompt styles

- content_scripts/setupMenuBar.js
Goes with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/521
> adds Activate Profiler to Develop menu, with I key as shortcut

- content_scripts/CameraFollowCoordinator.js
- content_scripts/desktopCamera.js
- added follow/unfollow camera on playback messages to spatial video tool
- updated follow functions to work with both menu bar and tool
- blurred/focused spatial video envelopes when switching follow targets
> Follow camera update

- content_scripts/desktopRenderer.js
Goes with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/544
> Only swap to originalMaterial on mobile

- content_scripts/MenuBar.js
- content_scripts/desktopRenderer.js
- content_scripts/setupMenuBar.js
Also adds try-catch around MenuBar keyboard shortcuts, to limit damage if one of them has an error in their implementation
Goes with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/573
> remove H keyboard shortcut, since function has been removed

- interfaces/remoteOperatorUI/index.js
the remote operator ui should run in the same mode as the main server
depends on:
https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/633
https://github.com/ptcrealitylab/pop-up-onboarding-addon/pull/113
https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/997
https://github.com/ptcrealitylab/vuforia-spatial-toolbox-ios-swift/pull/593
> Enable https

- .gitignore
- content_scripts/VirtualCamera.js
- content_styles/remoteOperator.css
- updated notification styles for camera modes to appear in bottom left corner
- created notification container where other notifications can be appended
> Notification update

- content_scripts/CameraVisCoordinator.js
- content_scripts/VirtualCamera.js
- content_scripts/WebRTCCoordinator.js
- content_scripts/desktopCamera.js
- content_scripts/desktopRenderer.js
- content_scripts/multiclientUI.js
- content_styles/remoteOperator.css
The last of my gs-upload-test PRs. This one mostly just adds the new avatar lockOnMode to the camera system, which enables "Follow", "Follow Me", and "All Follow Me". Plus some visual feedback for that following system, and small updates to desktopRenderer to load the system correctly even if the glb file doesn't exist yet in an empty session (but load the glb when it exists)
> LockOnMode, initialization updates for empty worlds, alignment correction

- content_scripts/desktopAdapter.js
lets three.js manage the update cycle (needed for WebXR compatibility)
depends on:
https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/655
> Threejs controlled animation loop

- content_scripts/VirtualCamera.js
- content_scripts/desktopCamera.js
- content_scripts/desktopRenderer.js
update camera system to initialize the virtual camera as soon as an object is detected, but update the virtualCamera floorOffset when the navmesh is calculated
> Initialize camera immediately; update virtualCamera floorOffset when navmesh calculated

- content_scripts/setupMenuBar.js
Had a spontaneous thought to add this for Teams, what do you think?
> Adds button to Help menu to trigger page reload

- content_scripts/WebRTCCoordinator.js
updated function name in WebRTCCoordinator to reflect name change in userinterface
> updated function name

- content_scripts/WebRTCCoordinator.js
- interfaces/remoteOperatorUI/index.js
- package-lock.json
- Adapted codebase to use ToolSocket v2.0.0's API.
> Toolsocket updates

- content_scripts/WebRTCCoordinator.js
- updated showBannerNotification to reflect addition of html id property to text and container divs in function arguments
_update along with pr #670 in userinterface_
> updated showError function to reflect changes to showBannerNotification

- content_scripts/MenuBar.js
adds a set text function to menu items to change text at runtime. This enables state information to be shown.
> Global scale & temp vr button

- content_scripts/VirtualCamera.js
- content_scripts/setupMenuBar.js
Implemented raycasting on Gaussian Splatting models, with some tricks to keep the FPS almost the same as the non-raycasting version while navigating in the 3D scene. Need user-interface to work.
1. toggle on/off raycasting in remote-operator/VirtualCamera.js
> GS Raycasting

- content_scripts/desktopCamera.js
Goes with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/754
> camera rotations interacts properly with full2d windows

- content_scripts/VirtualCamera.js
- content_scripts/desktopCamera.js
Also lets you click the following info button to stop following, in addition to pressing escape.
> Preserves your current camera position when you stop following another user
